### PR TITLE
PR

### PR DESCRIPTION
**Pull request by gorobot-nz**

### CODE REVIEW

**Comment by gorobot-nz** [comment]
The result of the last 2 days: 
- I read guides about elastic from links
- My app don't connected to elastic container
- I have questions about versions of libraries
- I did not implement all methods of repository
- I can't check implemented methods as elastic client doesn't work

**Comment by rast1025** [comment]
```
version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=$ES_LOGIN
      - ELASTIC_PASSWORD=$ES_PASSWORD
      - xpack.security.enabled=true
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_USERNAME=$ES_LOGIN
      - ELASTICSEARCH_PASSWORD=$ES_PASSWORD
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

**Comment by rast1025** [comment]
Try this one

**Comment by gorobot-nz** [comment]
As i understand, my app did not have enough time to connect to elastic in compose
When i try to run it as you recommended, i have unauthorized error
`
panic: elastic: Error 401 (Unauthorized)

goroutine 1 [running]:

go-tech-task/internal/book/repository/elastic_book.NewBooksElasticStorage() /home/nikita/go-tech-task/internal/book/repository/elastic_book/book_elastic.go:47 +0x4d5
go-tech-task/internal/server.NewApp() /home/nikita/go-tech-task/internal/server/server.go:76 +0xde
main.main() /home/nikita/go-tech-task/cmd/api/main.go:12 +0x4a
exit status 2
`

I tried to fix it by elastic.SetBasicAuth(), but it doesn't work

**Comment by gorobot-nz** [comment]
[https://olivere.github.io/elastic/](url)

`{"level":"fatal","msg":"error elastic: Error 400 (Bad Request): Failed to parse content to map [type=parse_exception]","time":"2022-01-05T17:55:42+03:00"}
exit status 1`

As i understand, the error occurred due to compose (удфыешс did not have time to setup while the application was connecting)
Now i have error of index creation
(example was taken from link)

**Comment by gorobot-nz** [comment]
I fix all methods and connection, change params in usecase and repository for id from int64 to string
Questions:
- Are there any scripts as "wait-for-postgres.sh" for elastic? As i understand, my error was in connection time (app trying to connect to elastic in compose, but elastic was not configured in any restart)
- I can't get id field in "GetBooks" in response from elastic (later i remove this field from domain book). So this question is about fields of search (or maybe i will add it in the point with textsearch)
- How final domain.Book should looks like?

**Review by gorobot-nz — COMMENTED** [review]
I tried to add test analyzer, which i found in elastic docs by search "mapping filters", by i didn't find the way to use it in elastic go lib (I tried to find examples, but all examples were launched in clear elasticsearch. So I have a question: is it used in projects library like sqlx but for elastic?)
Another question is about query param title
What is the right way to check existence of this param?(if i use empty param in SearchSource, i have empty result)

**Comment by rast1025** [comment]
> I fix all methods and connection, change type in usecase and repository for id from int64 to string Questions:
> 
> * Are there any scripts as "wait-for-postgres.sh" for elastic? As i understand, my error was in connection time (app trying to connect to elastic in compose, but elastic was not configured in any restart)
> * I can't get id field in "GetBooks" in response from elastic (i can get id only in add, delete and update methods). So this question is about fields of search (or maybe i will add it in the point with textsearch)
> * How final domain.Book should looks like?

1. You can use [healthchecks](https://github.com/peter-evans/docker-compose-healthcheck) or make your container restart on failure
2. You can make elastic's `_id` field your  book's `id` field. It does not matter much right now

**Comment by rast1025** [comment]
> I tried to add test analyzer, which i found in elastic docs by search "mapping filters", by i didn't find the way to use it in elastic go lib (I tried to find examples, but all examples were launched in clear elasticsearch. So I have a question: is it used in projects library like sqlx but for elastic?) Another question is about query param title What is the right way to check existence of this param?(if i use empty param in SearchSource, i have empty result)

1. First you add an analyzer to your index. Something like:
```json{
  "settings": {
    "index": {
      "number_of_shards": 2,
      "number_of_replicas": 1,
      "analysis": {
        "analyzer": {
          "custom_russian": {
            "type": "custom",
            "tokenizer": "standard",
            "char_filter": [
              "custom_to_russian"
            ],
            "filter": [
              "lowercase"
            ]
          },
          "custom_english": {
            "type": "custom",
            "tokenizer": "standard",
            "char_filter": [
              "custom_to_english"
            ],
            "filter": [
              "lowercase"
            ]
          }
        },
        "char_filter": {
          "custom_to_russian": {
            "type": "mapping",
            "mappings": [
              "G => Г"
            ]
          },
          "custom_to_english": {
            "type": "mapping",
            "mappings": [
              "Б => B"

            ]
          }
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "title": {
        "type": "text",
        "fields": {
          "en": {
            "type": "text",
            "analyzer": "custom_english"
          },
          "ru": {
            "type": "text",
            "analyzer": "custom_russian"
          }
        }
      }
    }
  }
}
```
And see, in mapping you add two new fields inside title field. They will create upon indexing new data. Later on you can a make a search inside those fields using `elastic.NewMultiMatchQuery(title, "title", "title.en", "title.ru").Operator("and").Fuzziness("AUTO")`
2. You can use `binding:"required"`  or just `context.Query("title")`

**Comment by gorobot-nz** [comment]
warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /home/nikita/go-tech-task

I have such warning after swag init -g cmd/api/main.go
Docs are generated but swagger html returns failed fetch

**Comment by gorobot-nz** [comment]
Swagger works with Get requests, but other requests returns

TypeError: NetworkError when attempting to fetch resource.


</span></span>

**Pull request merged**
