### PR TITLE
#2

### PR DESCRIPTION
**Pull request by gorobot-nz**

### CODE REVIEW

**Comment by gorobot-nz** [comment]
I need complex review of my tests, 'cause I never do it earlier and I understand that something goes wrong now

**Comment by gorobot-nz** [comment]
Please write again cmd command for terminal stop
Docker-compose still doesn't work

**Comment by rast1025** [comment]
> Please write again cmd command for terminal stop Docker-compose still doesn't work

Please have a look at my latest commit

**Comment by rast1025** [comment]
> I need complex review of my tests, 'cause I never do it earlier and I understand that something goes wrong now

I added a sample test for `/books` handle for you.

**Review by rast1025 — APPROVED** [review]

**Pull request merged**
